language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# ./gradlew 권한 변경
before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r springboot2-web
  - mkdir -p deploy
  - mv springboot2-web.zip deploy/springboot2-web.zip

deploy:
  - provider: s3
    access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
    secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
    bucket: joct-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deploy: true


# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - lee98417716@gmail.com
