# main.yml의 최상단입니다.
#새로 추가된 내용입니다. (11) 
env:  
  S3_BUCKET_NAME: joct-springboot-build #버킷 이름
  PROJECT_NAME: aws-spring  #프로젝트 이름

name: deploy
on:
  release:
    types: [push]
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Grant excute permission for gradlew
      run: chmod +x ./gradlew
      shell: bash
      
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle
      run: ./gradlew clean build -x test
      shell: bash
      
    - name: Get crrent time
      uses: josStorer/get-current-time@v2.1.2
      with:
        format: YYYY-MM-DDTHH-mm-ss
        utcOffset: "+09:00"

    - name: Show Current Time
      run:  echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}"
      shell: bash

    - name: Make zip file
      run: zip -r ./$PROJECT_NAME.zip .         # 프로젝트 이름으로 압축시킴
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1      #aws에 해당 키로 접속
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./$PROJECT_NAME.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$PROJECT_NAME.zip

    

    # # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # # the publishing section of your build.gradle
    # - name: Publish to GitHub Packages
    #   run: ./gradlew publish
    #   env:
    #     USERNAME: ${{ github.actor }}
    #     TOKEN: ${{ secrets.GITHUB_TOKEN }}
